/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import static Proyecto.Player.contplayers;
import static Proyecto.Player.jugadores;
import java.awt.BorderLayout;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Justm
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    Player ul= Player.userlogged;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        this.jPanel1= new PanelImagen("/imagenes/Background2.jpg");
        this.setContentPane(this.jPanel1);
        initComponents();
        
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameMenuJuego = new javax.swing.JFrame();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jFrameConfig = new javax.swing.JFrame();
        jCheckBoxTutorial = new javax.swing.JCheckBox();
        jCheckBoxClasico = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jFrameMiPerfil = new javax.swing.JFrame();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlUser = new javax.swing.JLabel();
        jlPuntos = new javax.swing.JLabel();
        jlPartidas = new javax.swing.JLabel();
        jlHeroes = new javax.swing.JLabel();
        jlVillanos = new javax.swing.JLabel();
        jFrameUniverso = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBoxHeroes = new javax.swing.JCheckBox();
        jCheckBoxVillanos = new javax.swing.JCheckBox();
        jButton19 = new javax.swing.JButton();
        jFrameRank = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        jLabelRank = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jFrameBatallas = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabelUA = new javax.swing.JLabel();
        jLabelUH = new javax.swing.JLabel();
        jLabelPa = new javax.swing.JLabel();
        jLabelPH = new javax.swing.JLabel();
        jLabelPV = new javax.swing.JLabel();
        jFrameCargarPartida = new javax.swing.JFrame();
        jLabel21 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jFrameEliminarPArtida = new javax.swing.JFrame();
        jLabelEL = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jFrameMenuJuego.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrameMenuJuego.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jFrameMenuJuego.setSize(new java.awt.Dimension(420, 320));

        jButton9.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton9.setText("NUEVA PARTIDA");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton9MousePressed(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton10.setText("CARGAR PARTIDA");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton10MousePressed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton11.setText("ELIMINAR PARTIDA");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton11MousePressed(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel4.setText("STRATEGO MARVEL'S HEROES");

        jButton15.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton15.setText("REGRESAR");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton15MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jFrameMenuJuegoLayout = new javax.swing.GroupLayout(jFrameMenuJuego.getContentPane());
        jFrameMenuJuego.getContentPane().setLayout(jFrameMenuJuegoLayout);
        jFrameMenuJuegoLayout.setHorizontalGroup(
            jFrameMenuJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameMenuJuegoLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jFrameMenuJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrameMenuJuegoLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jFrameMenuJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76)))
                .addGap(63, 63, 63))
        );
        jFrameMenuJuegoLayout.setVerticalGroup(
            jFrameMenuJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameMenuJuegoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jFrameConfig.setSize(new java.awt.Dimension(400, 350));

        jCheckBoxTutorial.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jCheckBoxTutorial.setText("MODO TUTORIAL");
        jCheckBoxTutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBoxTutorialMousePressed(evt);
            }
        });

        jCheckBoxClasico.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jCheckBoxClasico.setText("MODO CLÁSICO");
        jCheckBoxClasico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBoxClasicoMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 22)); // NOI18N
        jLabel1.setText("ESCOJA EL MODO DE JUEGO");

        jLabel5.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel5.setText("CONFIGURACIÓN");

        jButton16.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton16.setText("REGRESAR");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton16MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jFrameConfigLayout = new javax.swing.GroupLayout(jFrameConfig.getContentPane());
        jFrameConfig.getContentPane().setLayout(jFrameConfigLayout);
        jFrameConfigLayout.setHorizontalGroup(
            jFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameConfigLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameConfigLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameConfigLayout.createSequentialGroup()
                        .addGroup(jFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxTutorial)
                            .addComponent(jCheckBoxClasico))
                        .addGap(106, 106, 106))))
            .addGroup(jFrameConfigLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton16)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrameConfigLayout.setVerticalGroup(
            jFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameConfigLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jCheckBoxClasico, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jFrameMiPerfil.setSize(new java.awt.Dimension(700, 350));

        jButton6.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jButton6.setText("LOG DE MIS ULTIMOS JUEGOS");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jButton7.setText("CAMBIAR MI PASSWORD");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jButton8.setText("CONECTAR A TWITTER");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton8MousePressed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jButton12.setText("ELIMINAR MI CUENTA");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton12MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel2.setText("MI PERFIL");

        jButton17.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jButton17.setText("REGRESAR");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton17MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel6.setText("USUARIO: ");

        jLabel7.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel7.setText("PUNTOS:");

        jLabel8.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel8.setText("PARTIDAS JUGADAS:");

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel9.setText("PARTIDAS (HEROES): ");

        jLabel10.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel10.setText("PARTIDAS (VILLANOS):");

        jlUser.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        jlUser.setText("          ");

        jlPuntos.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        jlPuntos.setText("          ");

        jlPartidas.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        jlPartidas.setText("          ");

        jlHeroes.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        jlHeroes.setText("          ");

        jlVillanos.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        jlVillanos.setText("          ");

        javax.swing.GroupLayout jFrameMiPerfilLayout = new javax.swing.GroupLayout(jFrameMiPerfil.getContentPane());
        jFrameMiPerfil.getContentPane().setLayout(jFrameMiPerfilLayout);
        jFrameMiPerfilLayout.setHorizontalGroup(
            jFrameMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameMiPerfilLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jFrameMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameMiPerfilLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlUser))
                    .addGroup(jFrameMiPerfilLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jlPuntos))
                    .addGroup(jFrameMiPerfilLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPartidas))
                    .addGroup(jFrameMiPerfilLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlHeroes))
                    .addGroup(jFrameMiPerfilLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jlVillanos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jFrameMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameMiPerfilLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jFrameMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7)))
                    .addGroup(jFrameMiPerfilLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton17))
                    .addComponent(jButton6))
                .addGap(30, 30, 30))
            .addGroup(jFrameMiPerfilLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrameMiPerfilLayout.setVerticalGroup(
            jFrameMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameMiPerfilLayout.createSequentialGroup()
                .addGroup(jFrameMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameMiPerfilLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton17))
                    .addGroup(jFrameMiPerfilLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jFrameMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jlUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrameMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jlPuntos))
                        .addGap(8, 8, 8)
                        .addGroup(jFrameMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jlPartidas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrameMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jlHeroes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrameMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jlVillanos))))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jFrameUniverso.setSize(new java.awt.Dimension(400, 250));

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel3.setText("UNIVERSO MARVEL");

        jButton13.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton13.setText("RANKING");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton13MousePressed(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton14.setText("BATALLAS");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton14MousePressed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton18.setText("REGRESAR");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton18MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jFrameUniversoLayout = new javax.swing.GroupLayout(jFrameUniverso.getContentPane());
        jFrameUniverso.getContentPane().setLayout(jFrameUniversoLayout);
        jFrameUniversoLayout.setHorizontalGroup(
            jFrameUniversoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameUniversoLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel3)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameUniversoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFrameUniversoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135))
        );
        jFrameUniversoLayout.setVerticalGroup(
            jFrameUniversoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameUniversoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton18)
                .addGap(48, 48, 48))
        );

        jDialog1.setSize(new java.awt.Dimension(500, 300));

        jComboBox1.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel11.setText("NUEVA PARTIDA");

        jLabel12.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel12.setText("ESCOGE UN CONTRICANTE:");

        jLabel13.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel13.setText("¿HEROES O VILLANOS?");

        jCheckBoxHeroes.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jCheckBoxHeroes.setText("HEROES");
        jCheckBoxHeroes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBoxHeroesMousePressed(evt);
            }
        });
        jCheckBoxHeroes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHeroesActionPerformed(evt);
            }
        });

        jCheckBoxVillanos.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jCheckBoxVillanos.setText("VILLANOS");
        jCheckBoxVillanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBoxVillanosMousePressed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton19.setText("¡JUGAR!");
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton19MousePressed(evt);
            }
        });
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton19)
                            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                                    .addComponent(jCheckBoxHeroes)
                                    .addGap(67, 67, 67))))
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxVillanos))
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel11)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(16, 16, 16)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addGap(7, 7, 7)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxVillanos)
                    .addComponent(jCheckBoxHeroes))
                .addGap(18, 18, 18)
                .addComponent(jButton19)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jFrameRank.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrameRank.setSize(new java.awt.Dimension(300, 500));

        jLabel14.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel14.setText("RANKING");

        jLabelRank.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabelRank.setText("jLabel15");

        jButton21.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jButton21.setText("ATRAS");
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton21MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jFrameRankLayout = new javax.swing.GroupLayout(jFrameRank.getContentPane());
        jFrameRank.getContentPane().setLayout(jFrameRankLayout);
        jFrameRankLayout.setHorizontalGroup(
            jFrameRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameRankLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jFrameRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRank)
                    .addGroup(jFrameRankLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton21)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jFrameRankLayout.setVerticalGroup(
            jFrameRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameRankLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addGap(35, 35, 35)
                .addComponent(jLabelRank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jFrameBatallas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrameBatallas.setSize(new java.awt.Dimension(400, 400));

        jLabel15.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel15.setText("BATALLAS");

        jLabel16.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel16.setText("USUARIOS ACTIVOS:");

        jLabel17.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel17.setText("USUARIOS CREADOS:");

        jLabel18.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel18.setText("PARTIDAS JUGADAS:");

        jLabel19.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel19.setText("PARTIDAS GANADAS HEROÉS:");

        jLabel20.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel20.setText("PARTIDAS GANADAS VILLANOS:");

        jButton20.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton20.setText("REGRESAR");
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton20MousePressed(evt);
            }
        });
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jLabelUA.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jLabelUA.setText("jLabel21");

        jLabelUH.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jLabelUH.setText("jLabel22");

        jLabelPa.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jLabelPa.setText("jLabel23");

        jLabelPH.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jLabelPH.setText("jLabel24");

        jLabelPV.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jLabelPV.setText("jLabel25");

        javax.swing.GroupLayout jFrameBatallasLayout = new javax.swing.GroupLayout(jFrameBatallas.getContentPane());
        jFrameBatallas.getContentPane().setLayout(jFrameBatallasLayout);
        jFrameBatallasLayout.setHorizontalGroup(
            jFrameBatallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameBatallasLayout.createSequentialGroup()
                .addGroup(jFrameBatallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameBatallasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20))
                    .addGroup(jFrameBatallasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(jFrameBatallasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17))
                    .addGroup(jFrameBatallasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18))
                    .addGroup(jFrameBatallasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19))
                    .addGroup(jFrameBatallasLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFrameBatallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPH)
                    .addComponent(jLabelPV)
                    .addComponent(jLabelPa)
                    .addComponent(jLabelUH)
                    .addComponent(jLabelUA))
                .addGap(34, 34, 34))
            .addGroup(jFrameBatallasLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrameBatallasLayout.setVerticalGroup(
            jFrameBatallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameBatallasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jFrameBatallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabelUA))
                .addGap(18, 18, 18)
                .addGroup(jFrameBatallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabelUH))
                .addGap(18, 18, 18)
                .addGroup(jFrameBatallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrameBatallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrameBatallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabelPH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrameBatallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabelPV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton20)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jFrameCargarPartida.setSize(new java.awt.Dimension(400, 400));

        jLabel21.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel21.setText("CARGAR PARTIDA");

        jButton22.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton22.setText("CARGAR");

        jButton23.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton23.setText("CANCELAR");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jFrameCargarPartidaLayout = new javax.swing.GroupLayout(jFrameCargarPartida.getContentPane());
        jFrameCargarPartida.getContentPane().setLayout(jFrameCargarPartidaLayout);
        jFrameCargarPartidaLayout.setHorizontalGroup(
            jFrameCargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameCargarPartidaLayout.createSequentialGroup()
                .addGroup(jFrameCargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameCargarPartidaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton22)
                        .addGap(47, 47, 47)
                        .addComponent(jButton23))
                    .addGroup(jFrameCargarPartidaLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jFrameCargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jFrameCargarPartidaLayout.setVerticalGroup(
            jFrameCargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameCargarPartidaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jFrameCargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton22)
                    .addComponent(jButton23))
                .addGap(42, 42, 42))
        );

        jFrameEliminarPArtida.setSize(new java.awt.Dimension(400, 400));

        jLabelEL.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabelEL.setText("eliminar PARTIDA");

        jButton24.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton24.setText("eliminar");

        jButton25.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton25.setText("CANCELAR");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jFrameEliminarPArtidaLayout = new javax.swing.GroupLayout(jFrameEliminarPArtida.getContentPane());
        jFrameEliminarPArtida.getContentPane().setLayout(jFrameEliminarPArtidaLayout);
        jFrameEliminarPArtidaLayout.setHorizontalGroup(
            jFrameEliminarPArtidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameEliminarPArtidaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton24)
                .addGap(34, 34, 34)
                .addComponent(jButton25)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jFrameEliminarPArtidaLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jFrameEliminarPArtidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabelEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrameEliminarPArtidaLayout.setVerticalGroup(
            jFrameEliminarPArtidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameEliminarPArtidaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelEL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jFrameEliminarPArtidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton24)
                    .addComponent(jButton25))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STRATEGO MARVEL");

        jPanel1.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton1.setText("STRATEGO – MARVEL HEROES!");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton2.setText("CONFIGURACION");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton3.setText("MI PERFIL");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton4.setText("UNIVERSO MARVEL");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton5.setText("CERRAR SESIÓN");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.jFrameMenuJuego.setVisible(true);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MousePressed
        this.jFrameMenuJuego.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton15MousePressed

    private void jButton16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MousePressed
        this.jFrameConfig.setVisible(false);
        this.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16MousePressed

    private void jButton17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MousePressed
        this.jFrameMiPerfil.setVisible(false);
        this.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17MousePressed

    private void jButton18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MousePressed
        this.jFrameUniverso.setVisible(false);
        this.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        this.jFrameConfig.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        this.jlUser.setText(ul.getNombre());
        this.jlPuntos.setText(""+ul.getPuntos());
        this.jlPartidas.setText(""+ul.getBueno()+ul.getMalo());
        this.jlHeroes.setText(""+ul.getBueno());
        this.jlVillanos.setText(""+ul.getMalo());
        this.jFrameMiPerfil.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
       this.jFrameUniverso.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        ul.setPsswd();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MousePressed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
       int x=JOptionPane.showConfirmDialog(this, "¿Desea cerrar sesión?");    
       if (x==0){
        Player.userlogged=null;
        ul= null;
        this.setVisible(false);
        MenuInicial.m.setVisible(true);
        (new Player()).setFile();
       } else if (x==1){
           JOptionPane.showMessageDialog(this, "Tenga buen día");
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MousePressed
        File f= new File(Player.userlogged.getNombre()+"/partidas");
        if (f.length()==0){
             JOptionPane.showMessageDialog(null,"¡NO HAY PARTIDAS DISPONIBLES!");
        } else{
            this.jFrameCargarPartida.setVisible(true);
            this.jFrameMenuJuego.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MousePressed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
    JOptionPane.showMessageDialog(null,"¡PROXIMAMENTE ESTARÁ DISPONIBLE!");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MousePressed

    private void jButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MousePressed
        JOptionPane.showMessageDialog(null,"¡CONECTAR A TWITTER PROXIMAMENTE ESTARÁ DISPONIBLE!");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MousePressed

    private void jButton12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MousePressed
    ul.eliminarCuenta();
    this.jFrameMiPerfil.setVisible(false);
    MenuInicial m= new MenuInicial();
    this.setVisible(false);
    m.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MousePressed

    private void jButton13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MousePressed
        
        Marvel t= new Marvel();
        this.jLabelRank.setText(t.message);
        this.jFrameRank.setVisible(true);
        this.jFrameUniverso.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13MousePressed

    private void jButton14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MousePressed
       this.jLabelUA.setText(Marvel.userA+"");
       this.jLabelUH.setText(Marvel.userH+"");
       this.jLabelPa.setText(Marvel.partidas+"");
       this.jLabelPH.setText(Marvel.cuantosBuenos+"");
       this.jLabelPV.setText(Marvel.cuantosMalos+"");
       this.jFrameBatallas.setVisible(true);
       this.jFrameUniverso.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14MousePressed

    private void jCheckBoxClasicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxClasicoMousePressed
        this.jCheckBoxTutorial.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxClasicoMousePressed

    private void jCheckBoxTutorialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxTutorialMousePressed
        this.jCheckBoxClasico.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTutorialMousePressed

    private void jButton9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MousePressed
       if (contplayers==1){
           JOptionPane.showMessageDialog(null, "Necesita crear al menos otro jugador para acceder a esta opcion");
       } else{
        this.setComboBox();
        this.jDialog1.setVisible(true);
        
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MousePressed

    private void jCheckBoxHeroesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHeroesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHeroesActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Player user= new Player();
        user.getPlayer2(this.jComboBox1.getSelectedItem().toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBoxHeroesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxHeroesMousePressed
        Jugar.heroes=1;  
        Jugar.villanos=2;
        this.jCheckBoxVillanos.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHeroesMousePressed

    private void jCheckBoxVillanosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxVillanosMousePressed
        Jugar.heroes=2;
        Jugar.villanos=1;  
        this.jCheckBoxHeroes.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxVillanosMousePressed

    private void jButton19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MousePressed
        MainFrame j= new MainFrame();
        Jugar g= new Jugar();
        j.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19MousePressed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MousePressed
        this.jFrameRank.setVisible(false);
        this.jFrameUniverso.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21MousePressed

    private void jButton20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MousePressed
        this.jFrameBatallas.setVisible(false);
        this.jFrameUniverso.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20MousePressed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MousePressed
        File f= new File(Player.userlogged.getNombre()+"/partidas");
        if (f.length()==0){
             JOptionPane.showMessageDialog(null,"¡NO HAY PARTIDAS DISPONIBLES!");
        } else{
            this.jFrameEliminarPArtida.setVisible(true);
            this.jFrameMenuJuego.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MousePressed
        ;
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBoxClasico;
    private javax.swing.JCheckBox jCheckBoxHeroes;
    private javax.swing.JCheckBox jCheckBoxTutorial;
    private javax.swing.JCheckBox jCheckBoxVillanos;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrameBatallas;
    private javax.swing.JFrame jFrameCargarPartida;
    private javax.swing.JFrame jFrameConfig;
    private javax.swing.JFrame jFrameEliminarPArtida;
    private javax.swing.JFrame jFrameMenuJuego;
    private javax.swing.JFrame jFrameMiPerfil;
    private javax.swing.JFrame jFrameRank;
    private javax.swing.JFrame jFrameUniverso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEL;
    private javax.swing.JLabel jLabelPH;
    private javax.swing.JLabel jLabelPV;
    private javax.swing.JLabel jLabelPa;
    private javax.swing.JLabel jLabelRank;
    private javax.swing.JLabel jLabelUA;
    private javax.swing.JLabel jLabelUH;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlHeroes;
    private javax.swing.JLabel jlPartidas;
    private javax.swing.JLabel jlPuntos;
    private javax.swing.JLabel jlUser;
    private javax.swing.JLabel jlVillanos;
    // End of variables declaration//GEN-END:variables

public void setComboBox(){
    if (contplayers>0){
    for (Player i: Player.jugadores) { 
        if (i!=null){
        this.jComboBox1.addItem(i.getNombre());
        }
    }
    }
} 




}